#!/usr/bin/env python3
"""Single source for the phonics games' word lists.

Writes two generated files from the lists below:
  - app/js/04c-data-phonics.js        (the data the games read)
  - tools/audio/phonics_manifest.csv  (audio rows: letters + every word)

Then run tools/audio/build_audio_map.py to fold these into AUDIO_MAP, and
tools/audio/generate_polly_audio.py to produce the clips. Edit the lists here,
never the generated files. Clips land under app/audio/phonics/.
"""
import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
JS_OUT = os.path.join(ROOT, 'app', 'js', '04c-data-phonics.js')
CSV_OUT = os.path.join(ROOT, 'tools', 'audio', 'phonics_manifest.csv')

LETTERS = list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')

CVC_WORDS = ['cat', 'dog', 'sun', 'hat', 'pig', 'cup', 'fox', 'pot', 'van', 'bat',
             'hen', 'net', 'bug', 'cap', 'fan', 'pen', 'map', 'nut', 'bed', 'bus',
             'jam', 'log', 'mud', 'rug', 'zip', 'top', 'mug', 'pin', 'red', 'big']

RHYME_FAMILIES = [
    {'end': 'at', 'words': ['cat', 'hat', 'bat', 'rat']},
    {'end': 'an', 'words': ['can', 'fan', 'man', 'van']},
    {'end': 'ig', 'words': ['pig', 'big', 'dig', 'wig']},
    {'end': 'un', 'words': ['sun', 'bun', 'fun', 'run']},
    {'end': 'og', 'words': ['dog', 'log', 'fog', 'jog']},
    {'end': 'ug', 'words': ['bug', 'rug', 'hug', 'mug']},
    {'end': 'en', 'words': ['hen', 'pen', 'ten', 'den']},
    {'end': 'ot', 'words': ['pot', 'hot', 'dot', 'cot']},
    {'end': 'op', 'words': ['top', 'hop', 'mop', 'pop']},
    {'end': 'ap', 'words': ['cap', 'map', 'nap', 'tap']},
]

SIGHT_WORDS = ['the', 'a', 'and', 'is', 'to', 'you', 'it', 'in', 'was', 'said',
               'he', 'she', 'we', 'me', 'see', 'look', 'go', 'up', 'my', 'like',
               'can', 'are', 'for', 'they', 'this', 'that', 'with', 'have', 'of',
               'on', 'at', 'so', 'no', 'yes', 'all', 'come', 'here', 'play', 'little']


def all_words():
    seen, out = set(), []
    for w in CVC_WORDS + [w for f in RHYME_FAMILIES for w in f['words']] + SIGHT_WORDS:
        if w not in seen:
            seen.add(w)
            out.append(w)
    return sorted(out)


def write_js():
    fams = ','.join('{end:%s,words:%s}' % (json.dumps(f['end']), json.dumps(f['words']).replace(' ', ''))
                    for f in RHYME_FAMILIES)
    lines = [
        '/* GENERATED by tools/phonics/build_phonics.py — do not hand-edit.',
        '   Word lists for the phonics games (Beginning Sounds!, Sound It Out!,',
        '   Rhyme Time!, Sight Words!). speakText() reads clips from app/audio/phonics/. */',
        'var PHONICS_LETTERS=%s;' % json.dumps(LETTERS).replace(' ', ''),
        'var CVC_WORDS=%s;' % json.dumps(CVC_WORDS).replace(' ', ''),
        'var RHYME_FAMILIES=[%s];' % fams,
        'var SIGHT_WORDS=%s;' % json.dumps(SIGHT_WORDS).replace(' ', ''),
        '',
    ]
    with open(JS_OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))


def write_csv():
    rows = [['Game', 'Track', 'File', 'Phrase']]
    t = 1
    for L in LETTERS:
        rows.append(['Phonics', t, 'phonics/letter_%s.mp3' % L.lower(), 'The letter %s' % L])
        t += 1
    for w in all_words():
        rows.append(['Phonics', t, 'phonics/word_%s.mp3' % w, w])
        t += 1
    with open(CSV_OUT, 'w', newline='', encoding='utf-8') as f:
        csv.writer(f).writerows(rows)
    return len(rows) - 1


def main():
    write_js()
    n = write_csv()
    print('wrote %s and %s (%d audio rows)' % (os.path.relpath(JS_OUT, ROOT), os.path.relpath(CSV_OUT, ROOT), n))


if __name__ == '__main__':
    main()
