/* Playroom home screen: game cards, School tab, onboarding, and new-profile creation. */
function scene(type){var b='<svg viewBox="0 0 520 210" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><rect width="520" height="210" fill="'+(type==='bop'?'#e8ecdb':'#f4e7cd')+'"/><circle cx="430" cy="41" r="23" fill="#f8d981"/><path d="M-20 144Q105 54 275 140T570 100V220H-20" fill="'+(type==='bop'?'#b9c9a1':'#c4cba0')+'"/><path d="M-20 196Q130 119 290 178T560 151V230H-20" fill="'+(type==='bop'?'#9bb789':'#a3bb86')+'"/><path d="M56 40h42m-17-9h36M300 40h36" stroke="#fffdf4" stroke-width="11" stroke-linecap="round"/>';
 if(type==='bop')b+='<g class="ready"><g transform="translate(60 47) scale(1.05)">'+mouseArt()+'</g><g transform="translate(262 91) scale(.7)">'+mouseArt()+'</g></g>';
 else if(type==='scurry')b+='<g transform="translate(50 100) scale(.6)">'+mouseArt()+'</g><path d="M95 154H180V100H280V150H370" stroke="#fff7d0" stroke-width="9" stroke-linecap="round" stroke-linejoin="round" fill="none" opacity=".85" stroke-dasharray="14 10"/><g transform="translate(200 88) scale(1.6)">'+mazeCheeseIcon()+'</g><g transform="translate(355 132) scale(1.6)">'+mazeHoleIcon()+'</g>';
 else if(type==='countries')b+='<rect x="210" y="35" width="120" height="150" rx="10" fill="#eee3c8" stroke="#b7a473" stroke-width="3"/><rect x="60" y="55" width="55" height="42" rx="6" fill="#6fae5c" transform="rotate(-8 88 76)"/><rect x="370" y="80" width="60" height="46" rx="6" fill="#c96b8f" transform="rotate(10 400 103)"/><rect x="240" y="60" width="30" height="26" rx="4" fill="#e8a33d"/><rect x="280" y="100" width="30" height="26" rx="4" fill="#4a90a4"/>';
 else if(type==='gauchos')b+='<g transform="translate(60 110) scale(1.1)">'+cowIcon()+'</g><g transform="translate(180 135) scale(.9)">'+cowIcon()+'</g><g transform="translate(340 90) scale(1.3)">'+corralIcon()+'</g>';
 else if(type==='peaks')b+='<path d="M180,190 L260,60 L320,150 L380,90 L460,190 Z" fill="#9fa8b0"/><path d="M260,60 L275,90 L260,84 L248,95 Z" fill="#fff"/><path d="M380,90 L390,105 L380,100 L372,110 Z" fill="#fff"/><g transform="translate(250 130) scale(1.2)">'+climberIcon()+'</g><g transform="translate(255 55) scale(1.1)">'+flagIcon()+'</g>';
 else if(type==='biomes')b+='<svg x="190" y="10" width="130" height="192" viewBox="330 -545 1075 1840" preserveAspectRatio="xMidYMid meet">'+saCountries.map(function(c){return '<path d="'+c.d+'" '+(c.t?'transform="'+c.t+'" ':'')+'fill="#e8dfc4" stroke="#b7a473" stroke-width="6"/>';}).join('')+saBiomes.map(function(bi){return '<circle cx="'+bi.cx+'" cy="'+bi.cy+'" r="'+bi.r+'" fill="'+bi.color+'" fill-opacity=".7" stroke="#5a4632" stroke-width="10"/>';}).join('')+'</svg><g transform="translate(45 90) scale(1.5)">'+habitatIcon('rainforest')+'</g><g transform="translate(370 88) scale(1.5)">'+habitatIcon('mountains')+'</g>';
 else if(type==='animals')b+='<g transform="translate(40 70) scale(1.5)">'+animalIcon('jaguar')+'</g><g transform="translate(180 60) scale(1.4)">'+animalIcon('toucan')+'</g><g transform="translate(300 78) scale(1.4)">'+animalIcon('capybara')+'</g><g transform="translate(410 66) scale(1.4)">'+animalIcon('penguin')+'</g><path d="M40 168h440" stroke="#8a9c6c" stroke-width="7" stroke-linecap="round" stroke-dasharray="20 16"/>';
 else if(type==='market')b+='<path d="M70 70h380l-24-34H94z" fill="#d9704f"/><path d="M70 70h380v14H70z" fill="#b9563a"/><rect x="96" y="84" width="328" height="96" rx="8" fill="#e9d7b0" stroke="#b7a473" stroke-width="3"/><g transform="translate(130 100) scale(1.1)">'+marketItemIcon('empanada')+'</g><g transform="translate(250 100) scale(1.1)">'+marketItemIcon('hat')+'</g><g transform="translate(360 112) scale(1.4)">'+coinIcon(5)+'</g><g transform="translate(392 138) scale(1.1)">'+coinIcon(1)+'</g>';
 else if(type==='timeline')b+='<path d="M40 140h440" stroke="#8a7a6a" stroke-width="6" stroke-linecap="round"/>'+[0,1,2,3].map(function(i){var x=90+i*108;return '<circle cx="'+x+'" cy="140" r="11" fill="#f4d06f" stroke="#5a4632" stroke-width="3"/><rect x="'+(x-38)+'" y="52" width="76" height="58" rx="9" fill="#fffdf4" stroke="#5a4632" stroke-width="3"/><path d="M'+(x-24)+' 70h48M'+(x-24)+' 84h32M'+(x-24)+' 96h40" stroke="#b7a473" stroke-width="5" stroke-linecap="round"/><path d="M'+x+' 110v18" stroke="#8a7a6a" stroke-width="3"/>';}).join('');
 else for(var i=0;i<4;i++)b+='<g transform="translate('+(22+i*113)+' '+(i%2?79:48)+') scale(.85)">'+flowerArt(flowerSpecies[i%flowerSpecies.length],flowerHues[(i*2)%flowerHues.length],1)+'</g>';
 return b+'<path d="M28 201l4-14 7 13m421 2 7-19 5 18m-256 4 4-12 7 11" fill="#708f5a"/></svg>';}
function catalogEntry(id){return GAME_CATALOG.filter(function(g){return g.id===id;})[0];}
function visibleGames(p){var en=p.enabledGames&&p.enabledGames.length?p.enabledGames:GAME_IDS;return GAME_CATALOG.filter(function(g){return en.indexOf(g.id)>=0;});}
function card(g,num,assignmentId){return '<article class="game-card" data-action="start" data-game="'+g.id+'"'+(assignmentId?' data-assignment="'+assignmentId+'"':'')+'><div class="scene">'+scene(g.id)+'<span class="scene-label">'+g.label+'</span></div><div class="card-body"><div class="card-title-row"><h2>'+g.title+'</h2>'+(num?'<span class="game-number">'+num+'</span>':'')+'</div><p>'+g.desc+'</p><button class="big-button wide '+(g.secondary?'secondary-button':'')+'" data-action="start" data-game="'+g.id+'"'+(assignmentId?' data-assignment="'+assignmentId+'"':'')+'>'+icon('play')+'Let’s '+g.verb+'!</button></div></article>';}
function playSection(p){
 var games=visibleGames(p);
 if(!games.length)return '<p class="hint">No games are turned on yet. Ask a grown-up to choose some in the Parent Area.</p>';
 return '<div class="section-heading"><h2>Pick your adventure</h2><span class="quiet">'+games.length+' game'+(games.length===1?'':'s')+' · endless smiles</span></div><section class="games" aria-label="Games">'+games.map(function(g,i){return card(g,String(i+1).length<2?'0'+(i+1):(i+1));}).join('')+'</section>';
}
function schoolSection(p){
 var assignments=p.assignments||[];
 var pending=assignments.filter(function(a){return a.recurring||!a.completed;});
 var done=assignments.filter(function(a){return a.completed&&!a.recurring;}).slice(-8).reverse();
 var body='';
 if(!pending.length&&!done.length){
  body='<p class="hint">No schoolwork yet. Ask a grown-up to assign something in the Parent Area.</p>';
 } else {
  if(pending.length)body+='<div class="section-heading"><h2>Ready for you</h2></div><section class="games" aria-label="Assigned games">'+pending.map(function(a){var g=catalogEntry(a.gameId);return g?card(g,null,a.id):'';}).join('')+'</section>';
  if(done.length)body+='<div class="section-heading"><h2>Great work!</h2></div><div class="done-list">'+done.map(function(a){var g=catalogEntry(a.gameId);return '<div class="done-row"><span>'+(g?g.title:a.gameId)+'</span><span class="quiet">'+new Date(a.completedAt).toLocaleDateString()+'</span><span class="points-chip">+'+(10+a.score)+'</span></div>';}).join('')+'</div>';
 }
 return '<div class="section-heading"><h2>My school work</h2><span class="quiet">'+(p.points||0)+' points earned</span></div>'+body;
}
function home(){var p=current();var pendingCount=(p.assignments||[]).filter(function(a){return !a.completed;}).length;shell('<main><section class="hero"><span class="little-spark" aria-hidden="true">✳</span><p class="eyebrow">A little world, all yours</p><div class="name-lockup">'+mascot(p.mascot,p.colors)+'<h1 class="name-title '+p.style+'">'+esc(p.name)+'’s playroom</h1></div><p class="hero-sub">Big discoveries. Little adventures. Let’s play.</p><span class="little-spark right" aria-hidden="true">✦</span></section><div class="home-tabs"><button class="tab-btn'+(homeTab==='play'?' active':'')+'" data-action="home-tab" data-value="play">Play</button><button class="tab-btn'+(homeTab==='school'?' active':'')+'" data-action="home-tab" data-value="school">School'+(pendingCount?' <span class="tab-badge">'+pendingCount+'</span>':'')+'</button></div>'+(homeTab==='school'?schoolSection(p):playSection(p))+'</main>'+footer());}
function welcome(){root.innerHTML='<main class="onboarding"><div class="welcome">'+brand()+'<div class="welcome-art">'+scene('bloom')+'</div><p class="eyebrow">Small people. Big adventures.</p><h1>Who’s ready to play?</h1><p>Your name. Your colors. Your own little world.<br>Let’s make a playroom just for you.</p><form id="welcome-form"><label class="sr-only" for="welcome-name">Your name</label><input id="welcome-name" name="name" type="text" maxlength="24" placeholder="Type your name" autocomplete="off" required><button class="big-button wide" type="submit">Make my playroom '+icon('spark')+'</button><div class="error" id="name-error" role="alert"></div></form><p class="hint">Grown-ups can help with this bit.<br>Names and settings stay on this computer.</p></div></main>';$('#welcome-form').onsubmit=function(e){e.preventDefault();createProfile($('#welcome-name').value);};}
function createProfile(name){name=name.trim().slice(0,24);if(!name){$('#name-error').textContent='Please enter a name.';return;}if(state.profiles.length>=24){toast('This computer already has 24 players.');return;}var p={id:id(),name:name,colors:copy(palettes[state.profiles.length%palettes.length]),mascot:'flower',style:'pop',pattern:'dots',difficulty:sanitizeDifficulty({}),enabledGames:GAME_IDS.slice(),enabledDifficulties:DIFF_LEVELS.slice(),assignments:[],points:0,best:sanitizeBest(null)};state.profiles.push(p);state.active=p.id;save();closeModal();uiScreen='home';render();tone('hello');}
